version: '3'
services:
  nginx:
    image: nginx:1.13.12
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./:/var/www
    ports:
    - 8080:80

  gulp:
    build: .
    volumes:
    - ./:/var/www
    - /var/www/node_modules
