version: '2'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      VIRTUAL_HOST: lightnet328.com
      LETSENCRYPT_HOST: lightnet328.com
      LETSENCRYPT_EMAIL: lightnet328@gmail.com
    restart: always

networks:
  default:
    external:
      name: shared
